import { EXAM_DEFAULT } from './examDefault.mjs'

export const LOP6_ON_LUYEN = {
  'l6-on-luyen-chinh-phuc-diem-10': {
    title: '⭐ Chinh Phục Điểm 10 Toán 6',
    theory: {
      cards: [
        {
          title: 'Bộ công thức nền tảng cần nhớ chắc',
          formulas: [
            'S=\\dfrac{n(u_1+u_n)}{2}',
            'a=b\\cdot q+r\\ (0\\le r<b)',
            'ƯCLN(a,b)\\times BCNN(a,b)=a\\times b',
          ],
          legend: [
            'S: tổng dãy cách đều; n: số số hạng; u_1, u_n: số hạng đầu và cuối',
            'q: thương, r: số dư khi chia a cho b',
          ],
          note: 'Mẹo: khi đề bài cho "chia hết đồng thời cho nhiều số", hãy nghĩ ngay đến BCNN thay vì thử từng số một.',
        },
        {
          title: 'Kỹ thuật hay dùng ở câu khó nhất đề',
          formulas: ['(a-b)(a+b)=a^2-b^2', '|x|=k\\ (k\\ge0) \\Rightarrow x=k\\ \\text{hoặc}\\ x=-k'],
          legend: [
            'Hằng đẳng thức hiệu hai bình phương giúp tách/nhóm số hạng khi tính nhanh',
            'Với phương trình chứa dấu giá trị tuyệt đối, luôn xét đủ 2 trường hợp',
          ],
          note: 'Mẹo: gặp bài "tìm số lớn nhất/nhỏ nhất thỏa mãn", hãy đặt cận (chặn trên/dưới) trước, rồi xét các giá trị nguyên trong khoảng đó thay vì đoán mò.',
        },
      ],
    },
    video: { caption: '00:00 / 18:20 — chinh_phuc_diem_10_toan6_baigiang.mp4' },
    quiz: [
      { question: 'Tính nhanh: 1 + 2 + 3 + ... + 100.', options: ['5050', '5000', '5100', '4950'], correctIndex: 0 },
      { question: 'Tìm ƯCLN(36, 60).', options: ['12', '6', '18', '24'], correctIndex: 0 },
      { question: 'Tính giá trị biểu thức: (-8) + 15 - (-5).', options: ['12', '2', '-12', '-2'], correctIndex: 0 },
      { question: 'Rút gọn phân số 18/24 về dạng tối giản.', options: ['3/4', '2/3', '9/12', '6/8'], correctIndex: 0 },
      { question: 'Một hình chữ nhật có chiều dài 12cm, chiều rộng 7cm. Tính chu vi.', options: ['38 cm', '19 cm', '84 cm', '42 cm'], correctIndex: 0 },
    ],
    essays: [
      {
        prompt: 'Bài 1. Tính giá trị biểu thức: A = 3² × 5 − (17 − 9) × 2.',
        solution: ['$3^2=9,\\ 9\\times5=45$', '$17-9=8,\\ 8\\times2=16$', '$A=45-16=29$'],
      },
      {
        prompt: 'Bài 2. Tìm số tự nhiên x biết: (x − 5) × 3 + 7 = 25.',
        solution: ['$(x-5)\\times3=25-7=18$', '$x-5=18:3=6$', '$x=11$'],
      },
      {
        prompt: 'Bài 3. Một đội xe chở hàng, ngày đầu chở 2/5 tổng số hàng, ngày hai chở 1/3 số hàng còn lại, ngày ba chở nốt 80 tấn còn lại. Tính tổng số hàng đội cần chở.',
        solution: [
          'Sau ngày 1 còn $\\dfrac35$ tổng số hàng',
          'Ngày 2 chở $\\dfrac13\\times\\dfrac35=\\dfrac15$, còn lại $\\dfrac35-\\dfrac15=\\dfrac25$',
          '$\\dfrac25$ tổng $=80 \\Rightarrow$ tổng $=200$ tấn',
        ],
      },
      {
        prompt: 'Bài 4. Tìm số tự nhiên nhỏ nhất chia hết cho cả 12 và 18.',
        solution: ['$12=2^2\\times3,\\ 18=2\\times3^2$', '$BCNN(12,18)=2^2\\times3^2=36$'],
      },
      {
        prompt: 'Bài 5. Ba điểm A, B, C thẳng hàng, B nằm giữa A và C. Biết AB = 15cm, AC = 40cm. Tính BC và so sánh AB với BC.',
        solution: ['$BC=AC-AB=40-15=25$cm', 'So sánh: $AB=15$cm $< BC=25$cm'],
      },
    ],
    flashcards: [
      { front: 'Công thức tổng dãy số cách đều', back: '$S=\\dfrac{n(u_1+u_n)}{2}$' },
      { front: 'ƯCLN(a,b) × BCNN(a,b)', back: '$=a\\times b$' },
      { front: 'Quy tắc dấu ngoặc với số nguyên', back: 'Bỏ dấu ngoặc có dấu "−" đằng trước: đổi dấu tất cả số hạng bên trong' },
      { front: 'Cách rút gọn phân số', back: 'Chia cả tử và mẫu cho ƯCLN của chúng' },
      { front: 'Công thức chu vi hình chữ nhật', back: '$P=2\\times(a+b)$' },
    ],
    exam: {
      ...EXAM_DEFAULT,
      mcq: [
        { question: 'Tính 45 + 38.', options: ['83', '73', '93', '82'], correctIndex: 0 },
        { question: 'Tính 90 − 37.', options: ['53', '63', '43', '57'], correctIndex: 0 },
        { question: 'Tính 12 × 6.', options: ['72', '62', '82', '66'], correctIndex: 0 },
        { question: 'Tính 84 : 7.', options: ['12', '11', '13', '14'], correctIndex: 0 },
        { question: 'Số đối của −9 là số nào?', options: ['9', '-9', '0', '19'], correctIndex: 0 },
        { question: 'Phân số 2/5 đọc là?', options: ['Hai phần năm', 'Năm phần hai', 'Hai phẩy năm', 'Năm phần năm'], correctIndex: 0 },
        { question: 'Tính (-15) + 8.', options: ['-7', '7', '-23', '23'], correctIndex: 0 },
        { question: 'Tìm ƯCLN(24, 36).', options: ['12', '6', '18', '24'], correctIndex: 0 },
        { question: 'Rút gọn phân số 15/20.', options: ['3/4', '4/5', '15/20', '5/4'], correctIndex: 0 },
        { question: 'Tính 3² + 4².', options: ['25', '7', '49', '12'], correctIndex: 0 },
        { question: 'Một hình vuông cạnh 9cm. Tính diện tích.', options: ['81 cm²', '36 cm²', '18 cm²', '72 cm²'], correctIndex: 0 },
        { question: 'Tìm BCNN(8, 12).', options: ['24', '48', '12', '96'], correctIndex: 0 },
        { question: 'Tìm x biết: 2x + 5 = 17.', options: ['6', '5', '7', '11'], correctIndex: 0 },
        { question: 'Một lớp có 40 học sinh, số học sinh nam bằng 3/5 số học sinh cả lớp. Tính số học sinh nữ.', options: ['16', '24', '20', '15'], correctIndex: 0 },
        { question: 'Tính giá trị biểu thức: (-3) × 4 + (-12) : 3.', options: ['-16', '-8', '16', '-4'], correctIndex: 0 },
      ],
      essays: [
        {
          prompt: 'Câu 1 (Thông hiểu). Tính giá trị biểu thức: B = 5² − 2 × (7 − 3).',
          solution: ['$5^2=25$', '$7-3=4,\\ 2\\times4=8$', '$B=25-8=17$'],
        },
        {
          prompt: 'Câu 2 (Vận dụng). Một cửa hàng có 300kg gạo. Ngày đầu bán 1/4 số gạo, ngày sau bán 2/5 số gạo còn lại. Hỏi cửa hàng còn lại bao nhiêu kg gạo?',
          solution: [
            'Ngày đầu bán $300\\times\\dfrac14=75$kg, còn lại $225$kg',
            'Ngày sau bán $225\\times\\dfrac25=90$kg',
            'Còn lại: $225-90=135$kg',
          ],
        },
      ],
    },
    practiceBank: [
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-01', difficulty: 'nhan-biet', prompt: 'Tính 156 + 289.', solution: ['$156+289=445$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-02', difficulty: 'nhan-biet', prompt: 'Tính 502 − 187.', solution: ['$502-187=315$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-03', difficulty: 'nhan-biet', prompt: 'Tính 25 × 16.', solution: ['$25\\times16=400$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-04', difficulty: 'nhan-biet', prompt: 'Tính 144 : 12.', solution: ['$144:12=12$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-05', difficulty: 'nhan-biet', prompt: 'Tính 2⁵.', solution: ['$2^5=32$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-06', difficulty: 'nhan-biet', prompt: 'Tính (-12) + 20.', solution: ['$(-12)+20=8$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-07', difficulty: 'nhan-biet', prompt: 'Tính (-7) − 5.', solution: ['$(-7)-5=-12$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-08', difficulty: 'nhan-biet', prompt: 'Tính (-6) × (-4).', solution: ['$(-6)\\times(-4)=24$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-09', difficulty: 'nhan-biet', prompt: 'Rút gọn phân số 12/18.', solution: ['ƯCLN(12,18) $=6$', '$\\dfrac{12}{18}=\\dfrac23$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-10', difficulty: 'nhan-biet', prompt: 'Tính 3/4 + 1/4.', solution: ['$\\dfrac34+\\dfrac14=\\dfrac44=1$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-11', difficulty: 'nhan-biet', prompt: 'Tìm ƯCLN(18, 24).', solution: ['$18=2\\times3^2,\\ 24=2^3\\times3$', 'ƯCLN $=2\\times3=6$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-12', difficulty: 'nhan-biet', prompt: 'Tìm BCNN(4, 6).', solution: ['$4=2^2,\\ 6=2\\times3$', 'BCNN $=2^2\\times3=12$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-13', difficulty: 'nhan-biet', prompt: 'Số 84 có chia hết cho 7 không? Vì sao?', solution: ['$84=7\\times12$', 'Vậy 84 chia hết cho 7'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-14', difficulty: 'nhan-biet', prompt: 'Tính chu vi hình vuông cạnh 8cm.', solution: ['$4\\times8=32$cm'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-15', difficulty: 'nhan-biet', prompt: 'Tính diện tích hình chữ nhật dài 9cm, rộng 5cm.', solution: ['$9\\times5=45\\,cm^2$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-16', difficulty: 'nhan-biet', prompt: 'Tìm số đối của 15.', solution: ['Số đối của $15$ là $-15$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-17', difficulty: 'nhan-biet', prompt: 'Tính giá trị tuyệt đối của −23.', solution: ['$|-23|=23$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-18', difficulty: 'nhan-biet', prompt: 'Viết số thập phân 0,6 dưới dạng phân số tối giản.', solution: ['$0{,}6=\\dfrac{6}{10}=\\dfrac35$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-19', difficulty: 'nhan-biet', prompt: 'Tính 7³.', solution: ['$7^3=343$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nb-20', difficulty: 'nhan-biet', prompt: 'Ba điểm A, B, C thẳng hàng, B nằm giữa A và C, biết AB = 6cm, BC = 9cm. Tính AC.', solution: ['$AC=AB+BC=6+9=15$cm'] },

      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-01', difficulty: 'thong-hieu', prompt: 'Tính nhanh: 25 × 37 × 4.', solution: ['$25\\times4=100$', '$100\\times37=3700$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-02', difficulty: 'thong-hieu', prompt: 'Tính giá trị biểu thức: 3 × (8 + 12) − 20.', solution: ['$3\\times20=60$', '$60-20=40$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-03', difficulty: 'thong-hieu', prompt: 'Tìm x biết: x + 15 = 42.', solution: ['$x=42-15=27$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-04', difficulty: 'thong-hieu', prompt: 'Tính (-15) + 23 − 8.', solution: ['$(-15)+23=8$', '$8-8=0$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-05', difficulty: 'thong-hieu', prompt: 'Tìm ƯCLN(30, 45).', solution: ['$30=2\\times3\\times5,\\ 45=3^2\\times5$', 'ƯCLN $=3\\times5=15$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-06', difficulty: 'thong-hieu', prompt: 'Tìm BCNN(6, 8).', solution: ['$6=2\\times3,\\ 8=2^3$', 'BCNN $=2^3\\times3=24$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-07', difficulty: 'thong-hieu', prompt: 'Rút gọn phân số 24/36.', solution: ['ƯCLN(24,36) $=12$', '$\\dfrac{24}{36}=\\dfrac23$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-08', difficulty: 'thong-hieu', prompt: 'Tính 2/3 + 1/6.', solution: ['$\\dfrac23=\\dfrac46$', '$\\dfrac46+\\dfrac16=\\dfrac56$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-09',
        difficulty: 'thong-hieu',
        prompt: 'Một lớp có 45 học sinh, số học sinh giỏi chiếm 2/9 số học sinh cả lớp. Tính số học sinh giỏi.',
        solution: ['$45\\times\\dfrac29=10$ (học sinh)'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-10', difficulty: 'thong-hieu', prompt: 'Tính giá trị biểu thức: (-5) × 6 + 18 : (-3).', solution: ['$(-5)\\times6=-30$', '$18:(-3)=-6$', '$-30+(-6)=-36$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-11',
        difficulty: 'thong-hieu',
        prompt: 'Một hình chữ nhật có chu vi 36cm, chiều dài 12cm. Tính chiều rộng.',
        solution: ['Nửa chu vi: $36:2=18$cm', 'Chiều rộng: $18-12=6$cm'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-12', difficulty: 'thong-hieu', prompt: 'Tìm số tự nhiên nhỏ nhất chia hết cho cả 6 và 9.', solution: ['$6=2\\times3,\\ 9=3^2$', 'BCNN $=2\\times3^2=18$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-13', difficulty: 'thong-hieu', prompt: 'Tính 5² − 3³.', solution: ['$5^2=25,\\ 3^3=27$', '$25-27=-2$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-14',
        difficulty: 'thong-hieu',
        prompt: 'Một số tự nhiên chia cho 5 dư 3. Số đó có thể là số nào trong các số: 22, 26, 29, 33?',
        solution: ['Kiểm tra từng số: $22$ dư $2$, $26$ dư $1$, $29$ dư $4$, $33=6\\times5+3$ dư $3$', 'Vậy số cần tìm là $33$'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-15', difficulty: 'thong-hieu', prompt: 'Tính chu vi tam giác đều cạnh 11cm.', solution: ['$3\\times11=33$cm'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-16', difficulty: 'thong-hieu', prompt: 'Tìm x biết: 3x − 4 = 17.', solution: ['$3x=17+4=21$', '$x=7$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-17',
        difficulty: 'thong-hieu',
        prompt: 'So sánh hai phân số 3/5 và 5/8 bằng cách quy đồng.',
        solution: ['Quy đồng mẫu $40$: $\\dfrac35=\\dfrac{24}{40}$, $\\dfrac58=\\dfrac{25}{40}$', 'Vì $24<25$ nên $\\dfrac35<\\dfrac58$'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-18', difficulty: 'thong-hieu', prompt: 'Tính giá trị biểu thức: 100 − 2 × (15 − 7).', solution: ['$15-7=8,\\ 2\\times8=16$', '$100-16=84$'] },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-19', difficulty: 'thong-hieu', prompt: 'Cho đoạn thẳng MN = 20cm, I là trung điểm MN. Tính MI.', solution: ['$MI=20:2=10$cm'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-th-20',
        difficulty: 'thong-hieu',
        prompt: 'Một thùng có 60 lít nước, đã dùng hết 2/5 số nước. Hỏi còn lại bao nhiêu lít?',
        solution: ['Dùng: $60\\times\\dfrac25=24$ lít', 'Còn lại: $60-24=36$ lít'],
      },

      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-01',
        difficulty: 'van-dung',
        prompt: 'Tính nhanh: 1 + 3 + 5 + ... + 99 (tổng các số lẻ từ 1 đến 99).',
        solution: ['Số số hạng: $(99-1):2+1=50$', 'Tổng các số lẻ đầu tiên $=n^2$: $50^2=2500$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-02',
        difficulty: 'van-dung',
        prompt: 'Một số tự nhiên khi chia cho 4 dư 3, chia cho 5 dư 4. Tìm số nhỏ nhất thỏa mãn (khác 0).',
        solution: ['Chia 4 dư 3: $3,7,11,15,19,23,...$', 'Chia 5 dư 4: $4,9,14,19,24,...$', 'Số nhỏ nhất chung: $19$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-03',
        difficulty: 'van-dung',
        prompt: 'Tính giá trị biểu thức: A = (-25) + 18 − (-12) + (-5).',
        solution: ['$(-25)+18=-7$', '$-7-(-12)=5$', '$5+(-5)=0$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-04',
        difficulty: 'van-dung',
        prompt: 'Tìm ƯCLN và BCNN của 45 và 60, sau đó tính tích của chúng.',
        solution: ['$45=3^2\\times5,\\ 60=2^2\\times3\\times5$', 'ƯCLN $=15$, BCNN $=180$', 'Tích: $15\\times180=2700$ (đúng bằng $45\\times60$)'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-05',
        difficulty: 'van-dung',
        prompt: 'Một cửa hàng bán được 2/5 số vải trong ngày 1, 1/3 số vải còn lại trong ngày 2, còn lại 40m vải. Tính tổng số vải ban đầu.',
        solution: ['Sau ngày 1 còn $\\dfrac35$', 'Ngày 2 bán $\\dfrac13\\times\\dfrac35=\\dfrac15$, còn lại $\\dfrac35-\\dfrac15=\\dfrac25$', '$\\dfrac25$ tổng $=40 \\Rightarrow$ tổng $=100$m'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-06', difficulty: 'van-dung', prompt: 'Tìm x biết: (2x − 6) : 4 = 5.', solution: ['$2x-6=5\\times4=20$', '$2x=26 \\Rightarrow x=13$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-07',
        difficulty: 'van-dung',
        prompt: 'Tổng của ba số tự nhiên liên tiếp là 84. Tìm ba số đó.',
        solution: ['Số ở giữa: $84:3=28$', 'Ba số: $27, 28, 29$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-08',
        difficulty: 'van-dung',
        prompt: 'Một hình chữ nhật có chiều dài gấp đôi chiều rộng, chu vi 54cm. Tính diện tích.',
        solution: ['Nửa chu vi $=27=$ rộng $+$ dài $=3\\times$ rộng $\\Rightarrow$ rộng $=9$cm, dài $=18$cm', 'Diện tích: $9\\times18=162\\,cm^2$'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-09', difficulty: 'van-dung', prompt: 'Tính giá trị biểu thức: B = 2³ × 5 − 3² × 4.', solution: ['$2^3\\times5=40$', '$3^2\\times4=36$', '$B=40-36=4$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-10',
        difficulty: 'van-dung',
        prompt: 'Tìm số tự nhiên nhỏ nhất có 3 chữ số chia hết cho cả 4 và 6.',
        solution: ['$BCNN(4,6)=12$', '$100:12\\approx8{,}3$, số 3 chữ số nhỏ nhất chia hết cho 12 là $9\\times12=108$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-11',
        difficulty: 'van-dung',
        prompt: 'Một người đi xe đạp trong 3 giờ: giờ đầu đi được 12km, mỗi giờ sau đi nhiều hơn giờ trước 2km. Tính tổng quãng đường đi được.',
        solution: ['Giờ 1: $12$km, giờ 2: $14$km, giờ 3: $16$km', 'Tổng: $12+14+16=42$km'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-12', difficulty: 'van-dung', prompt: 'Tính giá trị biểu thức: (-3)² × (-2) + 15.', solution: ['$(-3)^2=9,\\ 9\\times(-2)=-18$', '$-18+15=-3$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-13',
        difficulty: 'van-dung',
        prompt: 'Một mảnh vườn hình vuông có chu vi bằng chu vi hình chữ nhật có chiều dài 15m, chiều rộng 9m. Tính diện tích mảnh vườn hình vuông.',
        solution: ['Chu vi hình chữ nhật: $2\\times(15+9)=48$m', 'Cạnh hình vuông: $48:4=12$m', 'Diện tích: $12\\times12=144\\,m^2$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-14',
        difficulty: 'van-dung',
        prompt: 'Tìm hai số biết tổng của chúng là 72 và tỉ số của chúng là 4/5.',
        solution: ['Tổng số phần: $4+5=9$, mỗi phần $=72:9=8$', 'Hai số: $32$ và $40$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-15',
        difficulty: 'van-dung',
        prompt: 'Tính nhanh: 2 + 4 + 6 + ... + 100 (tổng các số chẵn từ 2 đến 100).',
        solution: ['Số số hạng: $50$', 'Tổng: $50\\times(2+100):2=2550$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-16',
        difficulty: 'van-dung',
        prompt: 'Tìm số tự nhiên lớn nhất có 2 chữ số chia hết cho cả 3 và 5.',
        solution: ['$BCNN(3,5)=15$', 'Số 2 chữ số lớn nhất chia hết cho 15 là $90$'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-17', difficulty: 'van-dung', prompt: 'Tính giá trị biểu thức: C = 3/4 × 2/5 + 1/10.', solution: ['$\\dfrac34\\times\\dfrac25=\\dfrac{6}{20}=\\dfrac{3}{10}$', '$\\dfrac3{10}+\\dfrac1{10}=\\dfrac4{10}=\\dfrac25$'] },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-18',
        difficulty: 'van-dung',
        prompt: 'Cho đoạn thẳng AB = 48cm, M là trung điểm AB, N là trung điểm MB. Tính AN.',
        solution: ['$AM=48:2=24$cm', '$MN=24:2=12$cm', '$AN=AM+MN=24+12=36$cm'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-19',
        difficulty: 'van-dung',
        prompt: 'Một kho hàng nhập vào 250 tấn hàng, xuất đi 40% số hàng. Hỏi kho còn lại bao nhiêu tấn?',
        solution: ['Xuất đi: $250\\times40\\%=100$ tấn', 'Còn lại: $250-100=150$ tấn'],
      },
      { id: 'l6-on-luyen-chinh-phuc-diem-10-pb-vd-20', difficulty: 'van-dung', prompt: 'Tìm x biết: |x − 5| = 8.', solution: ['$x-5=8 \\Rightarrow x=13$', 'hoặc $x-5=-8 \\Rightarrow x=-3$'] },

      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-01',
        difficulty: 'nang-cao',
        prompt: 'Tìm số tự nhiên nhỏ nhất có tổng các chữ số bằng 24.',
        solution: [
          'Vì 2 chữ số có tổng tối đa $9+9=18<24$ nên số cần tìm có ít nhất 3 chữ số',
          'Với 3 chữ số, để số nhỏ nhất: chữ số hàng trăm nhỏ nhất có thể là $24-9-9=6$',
          'Số nhỏ nhất: $699$',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-02',
        difficulty: 'nang-cao',
        prompt: 'Tính tổng: 1×2 + 2×3 + 3×4 + ... + 9×10.',
        solution: ['Tách: $\\sum k(k+1)=\\sum k^2+\\sum k$', '$\\sum_{k=1}^{9}k^2=285,\\ \\sum_{k=1}^{9}k=45$', 'Tổng $=285+45=330$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-03',
        difficulty: 'nang-cao',
        prompt: 'Một số tự nhiên A chia cho 7 dư 5, chia cho 9 dư 4. Tìm số nhỏ nhất thỏa mãn (A > 0).',
        solution: ['Chia 7 dư 5: $5,12,19,26,33,40,...$', 'Chia 9 dư 4: $4,13,22,31,40,...$', 'Số nhỏ nhất chung: $40$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-04',
        difficulty: 'nang-cao',
        prompt: 'Tính giá trị biểu thức: D = (1 − 1/2)(1 − 1/3)(1 − 1/4)...(1 − 1/10).',
        solution: ['$D=\\dfrac12\\times\\dfrac23\\times\\dfrac34\\times...\\times\\dfrac{9}{10}$', 'Các thừa số triệt tiêu dây chuyền: $D=\\dfrac1{10}$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-05',
        difficulty: 'nang-cao',
        prompt: 'Ba số nguyên âm liên tiếp có tích bằng −120. Tìm ba số đó.',
        solution: ['Thử: $(-4)\\times(-5)\\times(-6)=20\\times(-6)=-120$', 'Ba số cần tìm: $-6, -5, -4$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-06',
        difficulty: 'nang-cao',
        prompt: 'Tìm hai số tự nhiên biết ƯCLN của chúng là 8, BCNN là 96, và tổng hai số là 56.',
        solution: [
          'Gọi $a=8m,\\ b=8n$ với ƯCLN(m,n)$=1$. Vì ƯCLN×BCNN$=a\\times b$ nên $mn=\\dfrac{8\\times96}{64}=12$',
          '$a+b=8(m+n)=56 \\Rightarrow m+n=7$',
          'Với $m+n=7,\\ mn=12$: $m=3,n=4$ (hoặc ngược lại) $\\Rightarrow a=24,\\ b=32$',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-07',
        difficulty: 'nang-cao',
        prompt: 'Tính tổng các số từ 1 đến 100 chia hết cho 3 hoặc chia hết cho 5.',
        solution: [
          'Tổng chia hết cho 3 (33 số hạng, đến 99): $3\\times\\dfrac{33\\times34}{2}=1683$',
          'Tổng chia hết cho 5 (20 số hạng, đến 100): $5\\times\\dfrac{20\\times21}{2}=1050$',
          'Tổng chia hết cho 15 (6 số hạng, đến 90): $15\\times\\dfrac{6\\times7}{2}=315$',
          'Theo nguyên lý bù trừ: $1683+1050-315=2418$',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-08',
        difficulty: 'nang-cao',
        prompt: 'Tính giá trị biểu thức: E = 2 + 2² + 2³ + ... + 2¹⁰.',
        solution: ['Tổng cấp số nhân công bội 2: $E=2^{11}-2$', '$2^{11}=2048$', '$E=2048-2=2046$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-09',
        difficulty: 'nang-cao',
        prompt: 'Một hình chữ nhật có chu vi 100cm, chiều dài lớn hơn chiều rộng (cả hai đều là số tự nhiên). Diện tích lớn nhất có thể là bao nhiêu?',
        solution: ['Nửa chu vi $=50$; để diện tích lớn nhất, 2 cạnh cần gần nhau nhất nhưng khác nhau: $26+24=50$', 'Diện tích lớn nhất: $26\\times24=624\\,cm^2$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-10',
        difficulty: 'nang-cao',
        prompt: 'Tìm hai số tự nhiên x, y (không nhất thiết khác nhau) biết x × y = 36 và x + y nhỏ nhất có thể.',
        solution: ['Với tích không đổi, tổng nhỏ nhất khi hai số gần nhau nhất', '$6\\times6=36$ vừa khớp $\\Rightarrow x=y=6$, tổng nhỏ nhất $=12$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-11',
        difficulty: 'nang-cao',
        prompt: 'Tính giá trị biểu thức: F = 1/(1×2) + 1/(2×3) + ... + 1/(9×10).',
        solution: ['Dùng $\\dfrac{1}{n(n+1)}=\\dfrac1n-\\dfrac1{n+1}$', 'Triệt tiêu dây chuyền: $F=1-\\dfrac1{10}=\\dfrac9{10}$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-12',
        difficulty: 'nang-cao',
        prompt: 'Một số tự nhiên có 2 chữ số, biết chữ số hàng chục hơn chữ số hàng đơn vị là 3, và tổng bình phương hai chữ số bằng 45. Tìm số đó.',
        solution: [
          'Gọi chữ số hàng đơn vị là $b$, hàng chục là $b+3$: $(b+3)^2+b^2=45$',
          'Thử $b=3$: $(6)^2+3^2=36+9=45$ đúng',
          'Số cần tìm: $63$',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-13',
        difficulty: 'nang-cao',
        prompt: 'Tìm số tự nhiên nhỏ nhất (lớn hơn 5) chia cho 3, 4, 5 đều dư 2.',
        solution: ['$BCNN(3,4,5)=60$', 'Số cần tìm: $60+2=62$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-14',
        difficulty: 'nang-cao',
        prompt: 'Cho A = 2 + 4 + 6 + ... + 2n = 210. Tìm n.',
        solution: ['Tổng $n$ số chẵn đầu tiên $=n(n+1)$', '$n(n+1)=210$; thử $n=14$: $14\\times15=210$ đúng', 'Vậy $n=14$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-15',
        difficulty: 'nang-cao',
        prompt: 'Ba lớp 6A, 6B, 6C có tổng 120 học sinh. Biết số học sinh lớp 6A bằng 2/5 tổng số, số học sinh 6B hơn 6C là 6 em. Tính số học sinh mỗi lớp.',
        solution: [
          '$6A=120\\times\\dfrac25=48$',
          '$6B+6C=120-48=72$ và $6B-6C=6$',
          '$6B=39,\\ 6C=33$',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-16',
        difficulty: 'nang-cao',
        prompt: 'Tính giá trị biểu thức: G = (-2)³ + (-3)² × (-1) − 10 : (-5).',
        solution: ['$(-2)^3=-8$', '$(-3)^2\\times(-1)=9\\times(-1)=-9$', '$10:(-5)=-2$', '$G=-8+(-9)-(-2)=-8-9+2=-15$'],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-17',
        difficulty: 'nang-cao',
        prompt: 'Tìm một phân số tối giản có giá trị nằm giữa 2/7 và 3/7, với mẫu số là số có 1 chữ số nhỏ nhất có thể (mẫu > 1).',
        solution: [
          'Mẫu $2$: $\\dfrac12=0{,}5$ không nằm giữa $\\dfrac27\\approx0{,}286$ và $\\dfrac37\\approx0{,}429$',
          'Mẫu $3$: $\\dfrac13\\approx0{,}333$ nằm giữa — thoả mãn',
          'Phân số cần tìm: $\\dfrac13$',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-18',
        difficulty: 'nang-cao',
        prompt: 'Một người gửi tiết kiệm: tháng đầu gửi 500 nghìn đồng, mỗi tháng sau gửi nhiều hơn tháng trước 50 nghìn đồng. Hỏi sau 10 tháng người đó gửi tổng cộng bao nhiêu tiền?',
        solution: [
          'Đây là dãy cách đều: $u_1=500,\\ u_{10}=500+9\\times50=950$ (nghìn đồng)',
          'Tổng: $10\\times(500+950):2=7250$ nghìn đồng $=7\\,250\\,000$đ',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-19',
        difficulty: 'nang-cao',
        prompt: 'Tìm tất cả các số tự nhiên có 2 chữ số biết số đó gấp 4 lần tổng các chữ số của nó.',
        solution: [
          'Gọi số $=10a+b$: $10a+b=4(a+b) \\Rightarrow 6a=3b \\Rightarrow b=2a$',
          'Với $a=1,2,3,4$ (vì $b\\le9$): các số là $12, 24, 36, 48$',
        ],
      },
      {
        id: 'l6-on-luyen-chinh-phuc-diem-10-pb-nc-20',
        difficulty: 'nang-cao',
        prompt: 'Cho biểu thức H = x² − 4x + 7 (x là số nguyên). Tìm giá trị nhỏ nhất của H và giá trị x tương ứng.',
        solution: ['$H=x^2-4x+7=(x-2)^2+3$', 'Vì $(x-2)^2\\ge0$ nên $H\\ge3$', 'Giá trị nhỏ nhất $H=3$ đạt tại $x=2$'],
      },
    ],
  },
}
